services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/NewsPaper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mermaid
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: NewsPaper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mermaid
    ports:
      - "5432:5433"


