version: '3.8'
services:
  spring-app:
    image: ulyashka/newspaper_spring_app:v4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/NewsPaper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mermaid
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: NewsPaper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mermaid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:


